- hosts: common
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
  roles:
  - role: inviqa.jumpcloud
  - role: user-management
  - role: gantsign.oh-my-zsh
    users:
      - username: "{{ jumpcloud_main_user }}"
  - role: jnv.unattended-upgrades
    when: ansible_os_family == "Debian"
  - role: packages
  - role: dotfiles

- hosts: cloud
  roles:
  - role: m4rcu5nl.zerotier-one

- hosts: docker
  roles:
    - role: geerlingguy.docker
      docker_users:
        - "{{ jumpcloud_main_user }}"

- hosts: rclone
  roles:
    - role: stefangweichinger.ansible_rclone

