- hosts: common
  remote_user: root
  tasks:
    - name: test connection
      ping:
      remote_user: root

    - name: install basic packages
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
        - vim
        - tmux
        - git
        - zsh
        - curl