- hosts: common,groups_common
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
  roles:
    - role: inviqa.jumpcloud
    - role: user-management
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ jumpcloud_main_user }}"
    - role: jnv.unattended-upgrades
      when: ansible_os_family == "Debian"
    - role: packages
    - role: dotfiles
  become: yes

- hosts: proxmox
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
  roles:
    - role: jnv.unattended-upgrades
      when: ansible_os_family == "Debian"
    - role: packages
  become: yes

- hosts: vm
  roles:
    - role: sbaerlocher.qemu-guest-agent
  become: yes

- hosts: zerotier
  roles:
    - role: zerotier
    - role: github-zt-dns
  become: yes

- hosts: docker
  roles:
    - role: geerlingguy.docker
      docker_users:
        - "{{ jumpcloud_main_user }}"
  become: yes

- hosts: rclone
  roles:
    - role: stefangweichinger.ansible_rclone
  become: yes
